# Generated by Django 4.0.4 on 2022-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='pf1',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='pf2',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='pf3',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='pf4',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='pf5',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='total_number',
            field=models.IntegerField(default=1, verbose_name='Общее количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='keywords',
            field=models.TextField(verbose_name='Ключевые слова (слово-%'),
        ),
    ]
