# Generated by Django 4.0.4 on 2022-06-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0002_point_pf1_point_pf2_point_pf3_point_pf4_point_pf5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='pf1',
        ),
        migrations.RemoveField(
            model_name='point',
            name='pf2',
        ),
        migrations.RemoveField(
            model_name='point',
            name='pf3',
        ),
        migrations.RemoveField(
            model_name='point',
            name='pf4',
        ),
        migrations.RemoveField(
            model_name='point',
            name='pf5',
        ),
    ]
